/*
 This file is part of JSlidingInfo v0.1

 JSlidingInfo is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 JSlidingInfo is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with JSlidingInfo.  If not, see <http://www.gnu.org/licenses/>.
 */
package sample;

import com.deepak.jslidinginfo.JSlidingInfo;

/**
 *
 * @author deepak
 */
public class Sample extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    public Sample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickMeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clickMeButton.setText("Click Me");
        clickMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(clickMeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(clickMeButton)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-402)/2, (screenSize.height-332)/2, 402, 332);
    }// </editor-fold>//GEN-END:initComponents

    private void clickMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickMeButtonActionPerformed
        // display the JSlidingInfo info

        JSlidingInfo.showInfo("JSlidingInfo\n\nDeveloped By: Deepak PK",
                JSlidingInfo.TYPE_SUCCESS,
                JSlidingInfo.POSITION_LEFT_TOP);

        JSlidingInfo.showInfo("This is a sliding info window",
                JSlidingInfo.TYPE_INFO,
                JSlidingInfo.POSITION_LEFT_VCENTRE);

        JSlidingInfo.showInfo("Display info from any \nof the 8 screen positions",
                JSlidingInfo.TYPE_WARNING,
                JSlidingInfo.POSITION_LEFT_BOTTOM);

        JSlidingInfo.showInfo("yep! from here also!",
                JSlidingInfo.TYPE_ERROR,
                JSlidingInfo.POSITION_BOTTOM_HCENTRE);

        JSlidingInfo.showInfo("provides sequential display of messages",
                JSlidingInfo.TYPE_FAIL,
                JSlidingInfo.POSITION_RIGHT_BOTTOM);

        JSlidingInfo.showInfo("you can put your own message icon!",
                JSlidingInfo.TYPE_PROCESSING,
                JSlidingInfo.POSITION_RIGHT_VCENTRE);

        JSlidingInfo.showInfo("control display duration and slide speed!",
                JSlidingInfo.TYPE_INFO,
                JSlidingInfo.POSITION_RIGHT_TOP);

        JSlidingInfo.showInfo("custom font, foreground & background color. Enough?",
                JSlidingInfo.TYPE_SUCCESS,
                JSlidingInfo.POSITION_TOP_HCENTRE);

    }//GEN-LAST:event_clickMeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sample().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickMeButton;
    // End of variables declaration//GEN-END:variables
}
